name: Clang_Format_Checker
on: [push, pull_request]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        extensions: 'cs'
        clangFormatVersion: 14
        inplace: True
        style: Microsoft
