name: Clang_Format_Checker
on: [push, pull_request]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v2.1.0
        with:
          sources: "**/*.cs"
          style: Microsoft