name: Clang_Format_Checker
on: [push, pull_request]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jidicula/clang-format-action@v4.5.0
        with:
          source: '.'
          extensions: 'cs'
          clangFormatVersion: 12
          inplace: True
          style: Microsoft