name: Test_Operation
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0' ]
      
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build
        run: dotnet build ./CSharp_Calculation/CSharp_Calculation.csproj --configuration Release
      - name: Test
        run: dotnet test ./Csharp_Test/Csharp_Test.sln --verbosity normal